// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_members.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
    RETURNING organization_id, user_id, role
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

type CreateOrganizationMemberRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (CreateOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i CreateOrganizationMemberRow
	err := row.Scan(&i.OrganizationID, &i.UserID, &i.Role)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT m.organization_id, m.role, o.name, o.type
FROM organization_members m
         JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1
  AND m.organization_id = $2
  AND m.deleted_at IS NULL
  AND o.deleted_at IS NULL
`

type GetOrganizationParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetOrganizationRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
}

func (q *Queries) GetOrganization(ctx context.Context, arg GetOrganizationParams) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, arg.UserID, arg.OrganizationID)
	var i GetOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.Role,
		&i.Name,
		&i.Type,
	)
	return i, err
}

const listUserOrganization = `-- name: ListUserOrganization :many
SELECT m.organization_id, m.role, o.name, o.type
FROM organization_members m
         JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1
  AND m.deleted_at IS NULL
  AND o.deleted_at IS NULL
ORDER BY m.joined_at
`

type ListUserOrganizationRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
}

func (q *Queries) ListUserOrganization(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganization, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationRow{}
	for rows.Next() {
		var i ListUserOrganizationRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Role,
			&i.Name,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
