// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_invitations.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE organization_invitations
SET status      = 'accepted',
    accepted_at = NOW(),
    accepted_by = $2
WHERE id = $1
  AND status = 'pending'
  AND expires_at > NOW()
`

type AcceptInvitationParams struct {
	ID         uuid.UUID  `json:"id"`
	AcceptedBy *uuid.UUID `json:"accepted_by"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.ID, arg.AcceptedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (organization_id,
                                      email,
                                      role,
                                      token_hash,
                                      invited_by,
                                      expires_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6) RETURNING
    id,
    organization_id,
    email,
    role,
    token_hash,
    invited_by,
    status,
    expires_at,
    accepted_at,
    accepted_by,
    created_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
	TokenHash      string    `json:"token_hash"`
	InvitedBy      uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const expireInvitation = `-- name: ExpireInvitation :execrows
UPDATE organization_invitations
SET status = 'expired'
WHERE id = $1
  AND status = 'pending'
  AND expires_at <= NOW()
`

func (q *Queries) ExpireInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT oi.id,
       oi.organization_id,
       oi.email,
       oi.role,
       oi.token_hash,
       oi.invited_by,
       oi.status,
       oi.expires_at,
       oi.accepted_at,
       oi.accepted_by,
       oi.created_at,
       o.name AS organization_name,
       u.name AS invited_by_name
FROM organization_invitations oi
         JOIN organizations o
              ON o.id = oi.organization_id
         JOIN users u
              ON u.id = oi.invited_by
WHERE oi.token_hash = $1 LIMIT 1
`

type GetInvitationByTokenHashRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Email            string             `json:"email"`
	Role             string             `json:"role"`
	TokenHash        string             `json:"token_hash"`
	InvitedBy        uuid.UUID          `json:"invited_by"`
	Status           string             `json:"status"`
	ExpiresAt        time.Time          `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy       *uuid.UUID         `json:"accepted_by"`
	CreatedAt        time.Time          `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
	InvitedByName    string             `json:"invited_by_name"`
}

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.InvitedByName,
	)
	return i, err
}

const getOrganizationInvitation = `-- name: GetOrganizationInvitation :one
SELECT id,
       organization_id,
       email,
       role,
       token_hash,
       invited_by,
       status,
       expires_at,
       accepted_at,
       accepted_by,
       created_at
FROM organization_invitations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationInvitation(ctx context.Context, id uuid.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getOrganizationInvitation, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOrganizationInvitation = `-- name: GetPendingOrganizationInvitation :one
SELECT id,
       organization_id,
       email,
       role,
       token_hash,
       invited_by,
       status,
       expires_at,
       accepted_at,
       accepted_by,
       created_at
FROM organization_invitations
WHERE organization_id = $1
  AND lower(email) = lower($2)
  AND status = 'pending' LIMIT 1
`

type GetPendingOrganizationInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

func (q *Queries) GetPendingOrganizationInvitation(ctx context.Context, arg GetPendingOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingOrganizationInvitation, arg.OrganizationID, arg.Email)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT oi.id,
       oi.organization_id,
       oi.email,
       oi.role,
       oi.token_hash,
       oi.invited_by,
       oi.status,
       oi.expires_at,
       oi.accepted_at,
       oi.accepted_by,
       oi.created_at,
       u.name AS invited_by_name
FROM organization_invitations oi
         JOIN users u
              ON u.id = oi.invited_by
WHERE oi.organization_id = $1
ORDER BY oi.created_at DESC
`

type ListInvitationsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	TokenHash      string             `json:"token_hash"`
	InvitedBy      uuid.UUID          `json:"invited_by"`
	Status         string             `json:"status"`
	ExpiresAt      time.Time          `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy     *uuid.UUID         `json:"accepted_by"`
	CreatedAt      time.Time          `json:"created_at"`
	InvitedByName  string             `json:"invited_by_name"`
}

func (q *Queries) ListInvitations(ctx context.Context, organizationID uuid.UUID) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.CreatedAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPendingOrganizationInvitations = `-- name: ListMyPendingOrganizationInvitations :many
SELECT oi.id,
       oi.organization_id,
       o.name AS organization_name,
       oi.role,
       oi.status,
       oi.expires_at,
       oi.created_at
FROM organization_invitations oi
         JOIN organizations o
              ON o.id = oi.organization_id
WHERE lower(oi.email) = lower($1)
  AND oi.status = 'pending'
  AND oi.expires_at > NOW()
ORDER BY oi.created_at DESC
`

type ListMyPendingOrganizationInvitationsRow struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	Role             string    `json:"role"`
	Status           string    `json:"status"`
	ExpiresAt        time.Time `json:"expires_at"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) ListMyPendingOrganizationInvitations(ctx context.Context, lower string) ([]ListMyPendingOrganizationInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listMyPendingOrganizationInvitations, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyPendingOrganizationInvitationsRow{}
	for rows.Next() {
		var i ListMyPendingOrganizationInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE organization_invitations
SET status = 'revoked'
WHERE id = $1
  AND organization_id = $2
  AND status = 'pending'
`

type RevokeInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
