// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, type)
VALUES ($1, $2)
    RETURNING id, name, type
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type CreateOrganizationRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Type string    `json:"type"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Type)
	var i CreateOrganizationRow
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}
