// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_members.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
    RETURNING organization_id, user_id, role
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

type CreateOrganizationMemberRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (CreateOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i CreateOrganizationMemberRow
	err := row.Scan(&i.OrganizationID, &i.UserID, &i.Role)
	return i, err
}
