// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    event_version,
    payload
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    event_version,
    payload,
    created_at,
    published_at,
    attempt_count,
    next_attempt_at,
    locked_at,
    locked_by,
    last_error
`

type CreateOutboxEventParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	EventVersion  int32     `json:"event_version"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
	)
	return i, err
}

const deletePublishedOutboxEvents = `-- name: DeletePublishedOutboxEvents :execrows
DELETE FROM outbox_events
WHERE published_at IS NOT NULL
  AND published_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeletePublishedOutboxEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutboxEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    event_version,
    payload,
    created_at,
    published_at,
    attempt_count,
    next_attempt_at,
    locked_at,
    locked_by,
    last_error
FROM outbox_events
WHERE published_at IS NULL
  AND (
    next_attempt_at IS NULL
        OR next_attempt_at <= NOW()
    )
  AND (
    locked_at IS NULL
        OR locked_at < NOW() - INTERVAL '5 minutes'
    )
ORDER BY created_at ASC, id ASC
    LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventVersion,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOutboxEvent = `-- name: LockOutboxEvent :exec
UPDATE outbox_events
SET
    locked_at = NOW(),
    locked_by = $2
WHERE id = $1
  AND published_at IS NULL
`

type LockOutboxEventParams struct {
	ID       uuid.UUID   `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) LockOutboxEvent(ctx context.Context, arg LockOutboxEventParams) error {
	_, err := q.db.Exec(ctx, lockOutboxEvent, arg.ID, arg.LockedBy)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    attempt_count = attempt_count + 1,
    next_attempt_at = $2,
    last_error = $3,
    locked_at = NULL,
    locked_by = NULL
WHERE id = $1
  AND published_at IS NULL
`

type MarkOutboxEventFailedParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET
    published_at = NOW(),
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL
WHERE id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const releaseOutboxEventLock = `-- name: ReleaseOutboxEventLock :exec
UPDATE outbox_events
SET
    locked_at = NULL,
    locked_by = NULL
WHERE id = $1
  AND published_at IS NULL
`

func (q *Queries) ReleaseOutboxEventLock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseOutboxEventLock, id)
	return err
}
