// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repository

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress *netip.Addr `json:"ip_address"`
	ExpiresAt time.Time   `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}
