// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_access.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const grantServiceAccess = `-- name: GrantServiceAccess :exec
INSERT INTO organization_service_access (organization_id, user_id, service_name, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id, user_id, service_name) DO NOTHING
`

type GrantServiceAccessParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	ServiceName    string    `json:"service_name"`
	GrantedBy      uuid.UUID `json:"granted_by"`
}

func (q *Queries) GrantServiceAccess(ctx context.Context, arg GrantServiceAccessParams) error {
	_, err := q.db.Exec(ctx, grantServiceAccess,
		arg.OrganizationID,
		arg.UserID,
		arg.ServiceName,
		arg.GrantedBy,
	)
	return err
}

const isServiceAccessAllowed = `-- name: IsServiceAccessAllowed :one
SELECT EXISTS(
    SELECT 1
    FROM organization_service_access
    WHERE organization_id = $1 AND user_id = $2 AND service_name = $3
) AS allowed
`

type IsServiceAccessAllowedParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	ServiceName    string    `json:"service_name"`
}

func (q *Queries) IsServiceAccessAllowed(ctx context.Context, arg IsServiceAccessAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isServiceAccessAllowed, arg.OrganizationID, arg.UserID, arg.ServiceName)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listServiceAccessByOrg = `-- name: ListServiceAccessByOrg :many
SELECT id, organization_id, user_id, service_name, granted_by, created_at
FROM organization_service_access
WHERE organization_id = $1
ORDER BY user_id, service_name
`

func (q *Queries) ListServiceAccessByOrg(ctx context.Context, organizationID uuid.UUID) ([]OrganizationServiceAccess, error) {
	rows, err := q.db.Query(ctx, listServiceAccessByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationServiceAccess{}
	for rows.Next() {
		var i OrganizationServiceAccess
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.ServiceName,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccessByOrgUser = `-- name: ListServiceAccessByOrgUser :many
SELECT id, organization_id, user_id, service_name, granted_by, created_at
FROM organization_service_access
WHERE organization_id = $1 AND user_id = $2
ORDER BY service_name
`

type ListServiceAccessByOrgUserParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) ListServiceAccessByOrgUser(ctx context.Context, arg ListServiceAccessByOrgUserParams) ([]OrganizationServiceAccess, error) {
	rows, err := q.db.Query(ctx, listServiceAccessByOrgUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationServiceAccess{}
	for rows.Next() {
		var i OrganizationServiceAccess
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.ServiceName,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllServiceAccess = `-- name: RevokeAllServiceAccess :exec
DELETE FROM organization_service_access
WHERE organization_id = $1 AND user_id = $2
`

type RevokeAllServiceAccessParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAllServiceAccess(ctx context.Context, arg RevokeAllServiceAccessParams) error {
	_, err := q.db.Exec(ctx, revokeAllServiceAccess, arg.OrganizationID, arg.UserID)
	return err
}

const revokeServiceAccess = `-- name: RevokeServiceAccess :execrows
DELETE FROM organization_service_access
WHERE organization_id = $1 AND user_id = $2 AND service_name = $3
`

type RevokeServiceAccessParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	ServiceName    string    `json:"service_name"`
}

func (q *Queries) RevokeServiceAccess(ctx context.Context, arg RevokeServiceAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeServiceAccess, arg.OrganizationID, arg.UserID, arg.ServiceName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
