// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signing_keys.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, private_key_encrypted, public_key, algorithm
FROM signing_keys
WHERE is_active = true
`

type GetActiveSigningKeyRow struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
}

func (q *Queries) GetActiveSigningKey(ctx context.Context) (GetActiveSigningKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i GetActiveSigningKeyRow
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyEncrypted,
		&i.PublicKey,
		&i.Algorithm,
	)
	return i, err
}

const getActiveSigningKeyAge = `-- name: GetActiveSigningKeyAge :one
SELECT kid, created_at
FROM signing_keys
WHERE is_active = true
`

type GetActiveSigningKeyAgeRow struct {
	Kid       string    `json:"kid"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetActiveSigningKeyAge(ctx context.Context) (GetActiveSigningKeyAgeRow, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKeyAge)
	var i GetActiveSigningKeyAgeRow
	err := row.Scan(&i.Kid, &i.CreatedAt)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :exec
INSERT INTO signing_keys (kid, private_key_encrypted, public_key, algorithm, is_active)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSigningKeyParams struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
	IsActive            bool   `json:"is_active"`
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) error {
	_, err := q.db.Exec(ctx, insertSigningKey,
		arg.Kid,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
		arg.Algorithm,
		arg.IsActive,
	)
	return err
}

const listActiveSigningKeys = `-- name: ListActiveSigningKeys :many
SELECT kid, private_key_encrypted, public_key, algorithm
FROM signing_keys
WHERE is_active = true
`

type ListActiveSigningKeysRow struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
}

func (q *Queries) ListActiveSigningKeys(ctx context.Context) ([]ListActiveSigningKeysRow, error) {
	rows, err := q.db.Query(ctx, listActiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSigningKeysRow{}
	for rows.Next() {
		var i ListActiveSigningKeysRow
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyEncrypted,
			&i.PublicKey,
			&i.Algorithm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSigningKeys = `-- name: ListPublishedSigningKeys :many
SELECT kid, private_key_encrypted, public_key, algorithm
FROM signing_keys
WHERE is_active = true
   OR (deactivated_at IS NOT NULL AND retired_at IS NULL)
`

type ListPublishedSigningKeysRow struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
}

// The JWKS document publishes the signing key AND keys awaiting retirement:
// an inactive key with no retired_at was deactivated by a rotation and its
// tokens may not have expired yet.
func (q *Queries) ListPublishedSigningKeys(ctx context.Context) ([]ListPublishedSigningKeysRow, error) {
	rows, err := q.db.Query(ctx, listPublishedSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedSigningKeysRow{}
	for rows.Next() {
		var i ListPublishedSigningKeysRow
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyEncrypted,
			&i.PublicKey,
			&i.Algorithm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireExpiredSigningKeys = `-- name: RetireExpiredSigningKeys :execrows
UPDATE signing_keys
SET retired_at = NOW()
WHERE is_active = false
  AND retired_at IS NULL
  AND deactivated_at IS NOT NULL
  AND deactivated_at < $1
`

func (q *Queries) RetireExpiredSigningKeys(ctx context.Context, deactivatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, retireExpiredSigningKeys, deactivatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSigningKey = `-- name: RotateSigningKey :exec
UPDATE signing_keys
SET is_active      = false,
    deactivated_at = NOW()
WHERE is_active = true
`

func (q *Queries) RotateSigningKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rotateSigningKey)
	return err
}
