// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signing_keys.sql

package repository

import (
	"context"
)

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, private_key_encrypted, public_key, algorithm
FROM signing_keys
WHERE is_active = true
`

type GetActiveSigningKeyRow struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
}

func (q *Queries) GetActiveSigningKey(ctx context.Context) (GetActiveSigningKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i GetActiveSigningKeyRow
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyEncrypted,
		&i.PublicKey,
		&i.Algorithm,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :exec
INSERT INTO signing_keys (kid, private_key_encrypted, public_key, algorithm, is_active)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSigningKeyParams struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicKey           string `json:"public_key"`
	Algorithm           string `json:"algorithm"`
	IsActive            bool   `json:"is_active"`
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) error {
	_, err := q.db.Exec(ctx, insertSigningKey,
		arg.Kid,
		arg.PrivateKeyEncrypted,
		arg.PublicKey,
		arg.Algorithm,
		arg.IsActive,
	)
	return err
}

const rotateSigningKey = `-- name: RotateSigningKey :exec
UPDATE signing_keys SET is_active = false WHERE is_active = true
`

func (q *Queries) RotateSigningKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rotateSigningKey)
	return err
}
