// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_devices.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveDeviceTokens = `-- name: ListActiveDeviceTokens :many
SELECT token
FROM user_devices
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) ListActiveDeviceTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserDevice = `-- name: RevokeUserDevice :one
UPDATE user_devices
SET revoked_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND token = $2
  AND revoked_at IS NULL
RETURNING id, platform
`

type RevokeUserDeviceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

type RevokeUserDeviceRow struct {
	ID       uuid.UUID `json:"id"`
	Platform string    `json:"platform"`
}

// Only the token's owner may revoke it; user_id comes from the JWT claims.
// No row returned = the token was never registered by this user (or is
// already revoked) and maps to ErrNotFound.
func (q *Queries) RevokeUserDevice(ctx context.Context, arg RevokeUserDeviceParams) (RevokeUserDeviceRow, error) {
	row := q.db.QueryRow(ctx, revokeUserDevice, arg.UserID, arg.Token)
	var i RevokeUserDeviceRow
	err := row.Scan(&i.ID, &i.Platform)
	return i, err
}

const upsertUserDevice = `-- name: UpsertUserDevice :one
INSERT INTO user_devices (user_id, token, platform, app_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) WHERE revoked_at IS NULL
DO UPDATE SET
    platform    = EXCLUDED.platform,
    app_version = EXCLUDED.app_version,
    updated_at  = now()
RETURNING id, user_id, created_at, updated_at
`

type UpsertUserDeviceParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Token      string      `json:"token"`
	Platform   string      `json:"platform"`
	AppVersion pgtype.Text `json:"app_version"`
}

type UpsertUserDeviceRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Re-registering an active token refreshes its platform/app metadata; a token
// that was revoked keeps its old row (the partial index only conflicts on
// active rows) and gets a fresh row instead.
func (q *Queries) UpsertUserDevice(ctx context.Context, arg UpsertUserDeviceParams) (UpsertUserDeviceRow, error) {
	row := q.db.QueryRow(ctx, upsertUserDevice,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.AppVersion,
	)
	var i UpsertUserDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
