// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, name)
VALUES ($1, $2, $3)
    RETURNING id, email, password, name
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type CreateUserRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, name, last_active_organization_id
FROM users
WHERE lower(email) = lower($1::text)
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                       uuid.UUID  `json:"id"`
	Email                    string     `json:"email"`
	Password                 string     `json:"password"`
	Name                     string     `json:"name"`
	LastActiveOrganizationID *uuid.UUID `json:"last_active_organization_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.LastActiveOrganizationID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, last_active_organization_id
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                       uuid.UUID  `json:"id"`
	Email                    string     `json:"email"`
	Name                     string     `json:"name"`
	LastActiveOrganizationID *uuid.UUID `json:"last_active_organization_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastActiveOrganizationID,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, email, name
FROM users
WHERE id = ANY($1::uuid[])
  AND deleted_at IS NULL
`

type GetUsersByIDsRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByIDsRow{}
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganization = `-- name: GetUsersByOrganization :many
SELECT
    u.id,
    u.email,
    u.name,
    COALESCE(m.role, '') AS role,
    (m.user_id IS NOT NULL)::boolean AS is_active
FROM users u
         LEFT JOIN organization_members m
                   ON m.user_id = u.id
                       AND m.organization_id = $1
                       AND m.deleted_at IS NULL
WHERE u.id = ANY($2::uuid[])
  AND u.deleted_at IS NULL
`

type GetUsersByOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Column2        []uuid.UUID `json:"column_2"`
}

type GetUsersByOrganizationRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
	Role     string    `json:"role"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) GetUsersByOrganization(ctx context.Context, arg GetUsersByOrganizationParams) ([]GetUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganization, arg.OrganizationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByOrganizationRow{}
	for rows.Next() {
		var i GetUsersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastActiveOrganization = `-- name: SetLastActiveOrganization :execrows
UPDATE users
SET last_active_organization_id = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetLastActiveOrganizationParams struct {
	ID                       uuid.UUID  `json:"id"`
	LastActiveOrganizationID *uuid.UUID `json:"last_active_organization_id"`
}

func (q *Queries) SetLastActiveOrganization(ctx context.Context, arg SetLastActiveOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLastActiveOrganization, arg.ID, arg.LastActiveOrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(email) = lower($1)
)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
